### ISSUE TITLE
3rd level is not working properly

### ISSUE THREAD

**Issue by premkv** [ploiu/Vanilla-JS-Accordions#3] opened 2021-11-10 09:19 UTC
i am adding 3rd level but it's giving me issue, the height is not adjusted as per the content and overflow is coming to 3rd level

**Comment by ploiu** [comment] 2021-11-10 12:08
Hi, thanks for reporting this issue! Could you please send me a code snippet that reproduces this bug? I'll take a look once I have time to.

**Comment by premkv** [comment] 2021-11-11 05:47
Hi, I attached the html.txt you can use the code and check the behavior and  images for refence 1, 2 and 3
In 3rd image the last link ( Basic Accordion - click me ) is not going down when i clicked the connectivity accordion and also the height of the body is not changing  

![1](https://user-images.githubusercontent.com/12591693/141245849-6f161667-90fa-4d74-96d4-6e1696f6eb24.PNG)
![2](https://user-images.githubusercontent.com/12591693/141245858-89655c76-e376-42e2-aceb-0d1d1eb78a18.PNG)
![3](https://user-images.githubusercontent.com/12591693/141246307-cf13c76e-8eec-4aaa-a23e-521ec94fcbb6.PNG)

**Comment by premkv** [comment] 2021-11-11 05:52
[html.txt](https://github.com/ploiu/Vanilla-JS-Accordions/files/7518080/html.txt)

**Comment by premkv** [comment] 2021-11-11 10:39
hi need your help please do the needful

**Comment by ploiu** [comment] 2021-11-11 12:47
> the last link ( Basic Accordion - click me ) is not going down when i clicked the connectivity accordion

That's because you have it set to reload the page when it's clicked - the entire window state is being reset and you have the accordion closed by default. If you remove `onclick="location.href=''"`, it should fix that issue. 

Right now, I'm working on adding tests so that I can detect bugs sooner, and there is an initial (yet still buggy) fix for the nested accordion issue. It should show all content, but it increases the height too much and I'm trying to fix that. If you want to try it out, take a look at the ui-tests branch.

**Comment by premkv** [comment] 2021-11-11 12:59
but i am not using the ( onclick="location.href=''") to clicked div

**Comment by premkv** [comment] 2021-11-11 13:07
hi, how to run in localhost,
i did the npm install after that which command should i run to start the project in a localhost

**Comment by ploiu** [comment] 2021-11-11 13:11
So you're expecting the Basic Accordion to expand when you click on the connectivity accordion? I'm confused on this.

For running the project in localhost, you will need to create an html file to test with and include the script and css files. If you're using intellij, it has native capabilities for running html files on localhost. If you're using VSCode, I suggest installing the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) plugin

**Comment by premkv** [comment] 2021-11-11 13:15
> Right now, I'm working on adding tests so that I can detect bugs sooner, and there is an initial (yet still buggy) fix for the nested accordion issue. It should show all content, but it increases the height too much and I'm trying to fix that. If you want to try it out, take a look at the ui-tests branch.

the above solution i am looking which you are doing in ( ui-tests branch) i checked in the html the height is increasing on every click. thanks for your support, till then i am searching for other multilevel accordion.

**Comment by ploiu** [comment] 2021-11-11 13:21
That's ok, good luck finding something that works for you!

**Closed as completed** 2021-11-11 17:44 UTC
